name: nikola
favicon: null
layout_spectrum: 0.49759
typography_spectrum: 0.10048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5797052597627044
  lightness: 0.8475869640242308
  saturation: 0.9901615814305842
  rhythmicContrast: 0.39494279702194035
purpose: []
